const PAGE_NAMES = {
  overview: 'نظرة عامة', content: 'استوديو المحتوى', library: 'مكتبة الوسائط',
  calendar: 'تقويم النشر', analytics: 'التحليلات', workflows: 'سير العمل',
  team: 'الفريق', settings: 'الإعدادات'
};
const PAGE_SUBTITLES = {
  overview: 'هذه لمحة عن نبض الاستوديو وما ينتظر إطلاقه اليوم.',
  content: 'خطّط، أنشئ، وراجع كل ما ينتجه فريقك في مكان واحد.',
  library: 'كل أصولك الإبداعية منظمة وجاهزة للاستخدام عبر القنوات.',
  calendar: 'نظرة واضحة على المحتوى القادم وما تم نشره.',
  analytics: 'تابع أداء المحتوى والقنوات واكتشف ما يلقى صدى أكبر.',
  workflows: 'أتمت المهام المتكررة واجعل مسارات الإنتاج أكثر سلاسة.',
  team: 'مساحة واحدة تجمع صنّاع المحتوى والمراجعين.',
  settings: 'خصص مساحة العمل بما يناسب طريقة فريقك.'
};
const initialContent = [
  {id:1,title:'حكاية العلامة — النسخة القصيرة',type:'فيديو قصير',channel:'Instagram',status:'review',date:'اليوم · ١٢:٣٠ م',symbol:'▶',cover:'',subtitle:'حملة الخريف · فيديو'},
  {id:2,title:'دليل الألوان لموسم الخريف',type:'منشور اجتماعي',channel:'LinkedIn',status:'production',date:'اليوم · ٣:٠٠ م',symbol:'◈',cover:'c2',subtitle:'هوية العلامة · تصميم'},
  {id:3,title:'ما وراء الكواليس: يوم في الاستوديو',type:'فيديو قصير',channel:'TikTok',status:'scheduled',date:'غداً · ١٠:٠٠ ص',symbol:'◉',cover:'c3',subtitle:'حياة الاستوديو · فيديو'},
  {id:4,title:'رسالة المؤسس إلى مجتمعنا',type:'منشور اجتماعي',channel:'Instagram',status:'draft',date:'٧ أكتوبر · ٤:٤٥ م',symbol:'✦',cover:'c4',subtitle:'قصة العلامة · كتابة'}
];
const initialTasks = [
  {id:1,title:'اعتماد نسخة فيديو إطلاق الخريف',meta:'المراجعة النهائية · اليوم',priority:'high',done:false},
  {id:2,title:'إضافة وصف بديل للأصول الجديدة',meta:'مكتبة الوسائط · اليوم',priority:'low',done:false},
  {id:3,title:'مشاركة موجز الحملة مع ليلى',meta:'حملة الخريف · غداً',priority:'',done:true}
];
const read = (key,fallback) => { try { const value=localStorage.getItem(key); return value?JSON.parse(value):fallback; } catch { return fallback; } };
const state = {
  content: read('aimedia.content',initialContent),
  tasks: read('aimedia.tasks',initialTasks),
  page: 'overview',
  filter: 'all',
  compact: read('aimedia.compact',false),
  notifications: 2
};
const $ = (selector,root=document) => root.querySelector(selector);
const $$ = (selector,root=document) => [...root.querySelectorAll(selector)];
const pageContent = $('#page-content');
const esc = value => String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const save = () => {
  localStorage.setItem('aimedia.content',JSON.stringify(state.content));
  localStorage.setItem('aimedia.tasks',JSON.stringify(state.tasks));
  localStorage.setItem('aimedia.compact',JSON.stringify(state.compact));
};
const dateLabel = new Intl.DateTimeFormat('ar',{weekday:'long',day:'numeric',month:'long'}).format(new Date());
$('#heading-eyebrow').textContent=dateLabel;
$('#today-label').textContent=new Intl.DateTimeFormat('ar',{day:'numeric',month:'short'}).format(new Date());
if(state.compact) document.body.classList.add('compact-mode');

function sparkline(color='#b7f36b',values=[4,8,5,12,9,18,15,23]) {
  const points=values.map((v,i)=>`${i*10},${30-v}`).join(' ');
  return `<svg class="kpi-spark" viewBox="0 0 70 30" aria-hidden="true"><polyline points="${points}" fill="none" stroke="${color}" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/><circle cx="70" cy="${30-values.at(-1)}" r="2.4" fill="${color}"/></svg>`;
}
function statusLabel(status){return ({review:'بانتظار المراجعة',production:'قيد الإنتاج',scheduled:'مجدول',draft:'مسودة'})[status]||status;}
function coverClass(cover){return `mini-cover ${cover||''}`.trim();}
function renderContentRows(items=state.content.slice(0,4)) {
  return items.map(item=>`<tr>
    <td><div class="content-title-cell"><span class="${coverClass(item.cover)}">${esc(item.symbol||'✦')}</span><div><div class="content-main-title">${esc(item.title)}</div><div class="content-subtitle">${esc(item.type)}</div></div></div></td>
    <td><span class="channel-tag">${esc(item.channel)}</span></td><td>${esc(item.date)}</td>
    <td><span class="status-pill ${esc(item.status)}">${statusLabel(item.status)}</span></td><td><button class="table-more" aria-label="خيارات">···</button></td>
  </tr>`).join('');
}
function renderTasks(){return state.tasks.map(task=>`<div class="task-row ${task.done?'completed':''}">
  <button class="task-check ${task.done?'done':''}" data-task="${task.id}" aria-label="${task.done?'إلغاء إكمال':'إكمال'} المهمة">${task.done?'✓':''}</button>
  <div class="task-content"><strong>${esc(task.title)}</strong><span>${esc(task.meta)}</span></div><i class="task-priority ${task.priority}"></i>
</div>`).join('');}
function renderOverview(){
  const bars1=[44,63,53,82,62,98,72],bars2=[29,41,38,53,48,61,56],days=['ث','ح','ن','ث','ر','خ','ج'];
  return `<section class="kpi-grid">
    <article class="kpi-card"><div class="kpi-top"><span>إجمالي الوصول</span><span class="kpi-icon green">⌁</span></div><div class="kpi-value-row"><strong class="kpi-value">248.6K</strong><span class="kpi-delta">↑ 18.4%</span></div><div class="kpi-note">مقارنة بآخر ٣٠ يوماً</div>${sparkline()}</article>
    <article class="kpi-card"><div class="kpi-top"><span>تفاعل الجمهور</span><span class="kpi-icon violet">♡</span></div><div class="kpi-value-row"><strong class="kpi-value">8.42%</strong><span class="kpi-delta">↑ 2.1%</span></div><div class="kpi-note">متوسط التفاعل عبر القنوات</div>${sparkline('#a897ff',[4,7,6,13,12,19,17,25])}</article>
    <article class="kpi-card"><div class="kpi-top"><span>محتوى قيد الإنتاج</span><span class="kpi-icon cyan">▤</span></div><div class="kpi-value-row"><strong class="kpi-value">${state.content.filter(x=>x.status==='production'||x.status==='review').length+7}</strong><span class="kpi-delta">↑ 3 هذا الأسبوع</span></div><div class="kpi-note">من الفكرة إلى المراجعة النهائية</div>${sparkline('#70d8de',[4,8,7,11,14,12,19,22])}</article>
    <article class="kpi-card"><div class="kpi-top"><span>المنشورات المجدولة</span><span class="kpi-icon orange">▦</span></div><div class="kpi-value-row"><strong class="kpi-value">12</strong><span class="kpi-delta">↑ 4 هذا الأسبوع</span></div><div class="kpi-note">القادم خلال الأيام السبعة</div>${sparkline('#ffbd76',[5,6,8,7,12,15,14,23])}</article>
  </section>
  <section class="dashboard-grid">
    <article class="panel"><div class="panel-heading"><div><h2 class="panel-title">نبض الاستوديو</h2><div class="panel-caption">الوصول والتفاعل على مدى الأسبوع</div></div><div class="chart-legend"><span class="legend-item"><i class="legend-dot"></i> الوصول</span><span class="legend-item"><i class="legend-dot violet"></i> التفاعل</span><select class="select-pill" id="chart-range" aria-label="الفترة"><option>آخر ٧ أيام</option><option>آخر ٣٠ يوماً</option><option>هذا العام</option></select></div></div>
    <div class="bar-chart">${days.map((day,i)=>`<div class="bar-group"><div class="bar-pair"><i class="bar secondary" style="height:${bars1[i]}%"></i><i class="bar" style="height:${bars2[i]}%"></i></div><span class="bar-label">${day}</span></div>`).join('')}</div>
    <div class="chart-summary"><span class="summary-stat">إجمالي الوصول <strong>248,620</strong></span><span class="summary-stat">متوسط التفاعل <strong>8.42%</strong></span></div></article>
    <article class="panel"><div class="panel-heading"><div><h2 class="panel-title">الأداء حسب القناة</h2><div class="panel-caption">توزيع التفاعل هذا الشهر</div></div><button class="icon-button tiny" data-page="analytics" aria-label="عرض التحليلات">↗</button></div>
      <div class="donut-wrap"><div class="donut"><svg viewBox="0 0 120 120"><circle cx="60" cy="60" r="45" fill="none" stroke="#303746" stroke-width="13"/><circle cx="60" cy="60" r="45" fill="none" stroke="#b7f36b" stroke-width="13" stroke-dasharray="113 170" stroke-linecap="round"/><circle cx="60" cy="60" r="45" fill="none" stroke="#a897ff" stroke-width="13" stroke-dasharray="70 213" stroke-dashoffset="-119" stroke-linecap="round"/><circle cx="60" cy="60" r="45" fill="none" stroke="#70d8de" stroke-width="13" stroke-dasharray="48 235" stroke-dashoffset="-195" stroke-linecap="round"/></svg><div class="donut-center"><strong>8.42%</strong><span>متوسط التفاعل</span></div></div>
      <div class="channel-legend"><div class="channel-row"><i class="channel-color"></i>Instagram<strong>42%</strong></div><div class="channel-row"><i class="channel-color v"></i>TikTok<strong>28%</strong></div><div class="channel-row"><i class="channel-color c"></i>YouTube<strong>19%</strong></div><div class="channel-row"><i class="channel-color o"></i>أخرى<strong>11%</strong></div></div></div>
    </article>
  </section>
  <section class="bottom-grid"><article class="panel"><div class="panel-heading"><div><h2 class="panel-title">على خط الإنتاج</h2><div class="panel-caption">آخر تحديثات المحتوى في الاستوديو</div></div><button class="text-link" data-page="content">عرض الكل ←</button></div><div class="table-wrap"><table class="content-table"><thead><tr><th>المحتوى</th><th>القناة</th><th>الموعد</th><th>الحالة</th><th></th></tr></thead><tbody>${renderContentRows()}</tbody></table></div></article>
  <article class="panel"><div class="panel-heading"><div><h2 class="panel-title">قائمة اليوم</h2><div class="panel-caption">${state.tasks.filter(t=>!t.done).length} مهام تحتاج انتباهك</div></div><button class="icon-button tiny" id="add-task" aria-label="إضافة مهمة">＋</button></div><div class="task-list">${renderTasks()}</div><div style="margin-top:11px"><button class="text-link" id="quick-task">＋ إضافة مهمة سريعة</button></div></article></section>`;
}
function contentView(){
  const items=state.filter==='all'?state.content:state.content.filter(c=>c.status===state.filter);
  return `<div class="panel"><div class="panel-heading"><div><h2 class="panel-title">كل المحتوى <span class="text-pill">${state.content.length}</span></h2><div class="panel-caption">إدارة مسودات الاستوديو ومراحل المراجعة</div></div><div style="display:flex;gap:7px;align-items:center"><select class="select-pill" id="content-filter"><option value="all" ${state.filter==='all'?'selected':''}>كل الحالات</option><option value="draft" ${state.filter==='draft'?'selected':''}>المسودات</option><option value="production" ${state.filter==='production'?'selected':''}>قيد الإنتاج</option><option value="review" ${state.filter==='review'?'selected':''}>للمراجعة</option><option value="scheduled" ${state.filter==='scheduled'?'selected':''}>مجدول</option></select><button class="button button-primary" data-new-content>＋ محتوى جديد</button></div></div>
  ${items.length?`<div class="table-wrap"><table class="content-table"><thead><tr><th>المحتوى</th><th>القناة</th><th>الموعد</th><th>الحالة</th><th></th></tr></thead><tbody>${renderContentRows(items)}</tbody></table></div>`:'<div class="empty-state"><strong>لا توجد عناصر بهذه الحالة</strong>أنشئ محتوى جديداً أو اختر حالة أخرى.</div>'}</div>
  <div class="section-top"><h3>ابدأ بسرعة</h3><span class="text-pill">قوالب الاستوديو</span></div><div class="page-grid"><article class="panel feature-card"><span class="feature-icon">✳</span><h3>فكرة إلى منشور</h3><p>حوّل ملاحظة أولية إلى موجز منشور اجتماعي جاهز للمراجعة.</p><div class="feature-foot">قالب محتوى · ٥ دقائق</div></article><article class="panel feature-card"><span class="feature-icon" style="color:var(--violet);background:#a897ff17">▶</span><h3>مخطط فيديو قصير</h3><p>قسّم الفكرة إلى مشاهد، لقطات، وتعليق صوتي.</p><div class="feature-foot">قالب إنتاج · ١٢ دقيقة</div></article><article class="panel feature-card"><span class="feature-icon" style="color:var(--cyan);background:#70d8de17">▤</span><h3>موجز حملة</h3><p>اجمع الهدف والجمهور والرسالة والقنوات في وثيقة واحدة.</p><div class="feature-foot">قالب تخطيط · ٨ دقائق</div></article></div>`;
}
function libraryView(){const assets=[['غلاف حملة الخريف','PNG · 2400 × 1600','✦',''],['لقطات الاستوديو — B-roll','MP4 · 00:42','▶','p2'],['مجموعة المنتجات، إصدار 02','JPG · 12 ملفاً','◈','p3'],['نظام الأيقونات الجديد','SVG · 24 أيقونة','✣','p4']];return `<div class="panel"><div class="panel-heading"><div><h2 class="panel-title">مكتبة الوسائط <span class="text-pill">${assets.length+18} أصل</span></h2><div class="panel-caption">منظمّة حسب الحملات والاستخدام</div></div><button class="button button-primary" id="upload-asset">↑ رفع أصل</button></div><div class="asset-grid">${assets.map(a=>`<article class="asset-card"><div class="asset-preview ${a[3]}">${a[2]}</div><div class="asset-info"><strong>${a[0]}</strong><span>${a[1]}</span></div></article>`).join('')}</div><div class="section-top"><h3>المجموعات</h3><button class="text-link" data-toast="إنشاء مجموعة يتطلب ربط التخزين الخلفي">＋ مجموعة جديدة</button></div><div class="page-grid"><article class="panel feature-card"><span class="feature-icon">◈</span><h3>حملة الخريف</h3><p>١٢ ملفاً · آخر تحديث اليوم</p></article><article class="panel feature-card"><span class="feature-icon" style="color:var(--violet);background:#a897ff17">✦</span><h3>هوية العلامة</h3><p>٨ ملفات · آخر تحديث ٣ أكتوبر</p></article><article class="panel feature-card"><span class="feature-icon" style="color:var(--cyan);background:#70d8de17">▶</span><h3>لقطات الفيديو</h3><p>١٥ ملفاً · آخر تحديث ٢ أكتوبر</p></article></div></div>`;}
function calendarView(){const week=['الأحد','الإثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'];const nums=[4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,1,2,3,4,5,6,7];return `<div class="panel"><div class="calendar-toolbar"><div><strong>أكتوبر ٢٠٢٦</strong><div class="panel-caption">١٢ منشوراً مجدولاً هذا الشهر</div></div><div style="display:flex;gap:7px"><button class="icon-button tiny" data-toast="عرض الشهر السابق">‹</button><button class="select-pill" data-toast="تمت العودة إلى تاريخ اليوم">اليوم</button><button class="icon-button tiny" data-toast="عرض الشهر التالي">›</button></div></div><div class="calendar-grid">${week.map(d=>`<div class="calendar-cell weekday">${d}</div>`).join('')}${nums.map((n,i)=>`<div class="calendar-cell ${n===6&&i<7?'today':''}"><b>${n}</b>${i===2?'<span class="calendar-event">ريلز: قصة العلامة</span>':''}${i===8?'<span class="calendar-event green">منشور: ألوان الخريف</span>':''}${i===13?'<span class="calendar-event">فيديو: خلف الكواليس</span>':''}${i===22?'<span class="calendar-event green">مقال: دليل الموسم</span>':''}</div>`).join('')}</div></div>`;}
function analyticsView(){return `<div class="analytics-grid"><article class="panel"><div class="panel-heading"><div><h2 class="panel-title">نمو الوصول</h2><div class="panel-caption">إجمالي المشاهدات خلال آخر ٣٠ يوماً</div></div><span class="status-pill scheduled">↑ 18.4%</span></div><div class="big-number">248,620</div><div class="chart-large">${[38,53,48,65,58,76,62,88,74,95,82,100].map(h=>`<i class="bar" style="height:${h}%"></i>`).join('')}</div><div class="chart-labels"><span>١ سبتمبر</span><span>٨ سبتمبر</span><span>١٥ سبتمبر</span><span>٢٢ سبتمبر</span><span>٣٠ سبتمبر</span></div></article><article class="panel"><div class="panel-heading"><div><h2 class="panel-title">التفاعل حسب القناة</h2><div class="panel-caption">معدل التفاعل مقارنة بالشهر الماضي</div></div><span class="select-pill">سبتمبر ٢٠٢٦</span></div>${[['Instagram','10.2%',78,'var(--accent)'],['TikTok','8.7%',63,'var(--violet)'],['YouTube','6.4%',46,'var(--cyan)'],['LinkedIn','4.1%',31,'var(--orange)']].map(x=>`<div style="margin:18px 0"><div style="display:flex;justify-content:space-between;font-size:10px;color:#aab2c0;margin-bottom:7px"><span>${x[0]}</span><strong>${x[1]}</strong></div><div class="usage-track"><span style="width:${x[2]}%;background:${x[3]}"></span></div></div>`).join('')}</article><article class="panel"><h2 class="panel-title">أفضل المحتويات</h2><div class="panel-caption">حسب معدل التفاعل</div><div class="content-list" style="margin-top:14px">${state.content.slice(0,3).map((x,i)=>`<div class="content-list-item"><span class="mini-cover ${x.cover}">${i+1}</span><div class="list-text"><strong>${esc(x.title)}</strong><p>${esc(x.channel)} · ${[12.8,10.3,9.1][i]}% تفاعل</p></div><span class="status-pill scheduled">↑</span></div>`).join('')}</div></article><article class="panel"><h2 class="panel-title">ملخص الأداء</h2><div class="panel-caption">مقارنة بآخر ٣٠ يوماً</div><div class="setting-row"><div class="setting-copy"><strong>نمو المتابعين</strong><small>صافي متابعين جدد</small></div><strong style="color:var(--accent)">+1,284</strong></div><div class="setting-row"><div class="setting-copy"><strong>مشاهدات الفيديو</strong><small>عبر كل القنوات</small></div><strong>86.2K</strong></div><div class="setting-row"><div class="setting-copy"><strong>أفضل وقت للنشر</strong><small>حسب تفاعل جمهورك</small></div><strong>٦:٣٠ م</strong></div></article></div>`;}
function workflowsView(){const flows=[['مراجعة المحتوى','كلما انتقل المحتوى إلى المراجعة، أرسل تنبيهاً للمراجع.','نشط','✎'],['تذكير موعد النشر','تنبيه قبل موعد النشر المجدول بساعتين.','نشط','◷'],['أرشفة الأصول','تصنيف الملفات الجديدة تلقائياً حسب اسم الحملة.','متوقف','▧']];return `<div class="panel"><div class="panel-heading"><div><h2 class="panel-title">مسارات العمل</h2><div class="panel-caption">أتمتة الخطوات المتكررة بين أعضاء فريقك</div></div><button class="button button-primary" data-toast="محرر الأتمتة يحتاج إلى خدمة خلفية قبل التفعيل">＋ مسار جديد</button></div><div class="content-list">${flows.map((f,i)=>`<div class="content-list-item"><span class="feature-icon" style="width:36px;height:36px">${f[3]}</span><div class="list-text"><strong>${f[0]}</strong><p>${f[1]}</p></div><span class="status-pill ${i===2?'draft':'scheduled'}">${f[2]}</span><button class="icon-button tiny" data-toast="إعدادات المسار ${f[0]}">···</button></div>`).join('')}</div><div class="section-top"><h3>كيف تعمل المسارات؟</h3></div><div class="page-grid"><article class="panel feature-card"><span class="feature-icon">①</span><h3>اختر محفزاً</h3><p>ابدأ عند إنشاء محتوى أو تغيير حالته أو اقتراب موعد نشره.</p></article><article class="panel feature-card"><span class="feature-icon" style="color:var(--violet);background:#a897ff17">②</span><h3>حدّد الإجراء</h3><p>أرسل إشعاراً، أو أنشئ مهمة، أو حدّث حالة عنصر.</p></article><article class="panel feature-card"><span class="feature-icon" style="color:var(--cyan);background:#70d8de17">③</span><h3>تابع التنفيذ</h3><p>راجع سجل التشغيل وعدّل المسار وفق احتياجات الفريق.</p></article></div></div>`;}
function teamView(){const people=[['YS','Yaslam S.','مدير مساحة العمل','مالك'],['LM','ليلى محمد','مخرجة إبداعية','عضو'],['OK','عمر خالد','محرر فيديو','عضو'],['NA','نور أحمد','استراتيجية محتوى','عضو']];return `<div class="panel"><div class="panel-heading"><div><h2 class="panel-title">فريق Northstar Studio</h2><div class="panel-caption">٤ أعضاء · مساحة خاصة</div></div><button class="button button-primary" id="invite-team">＋ دعوة عضو</button></div><div class="content-list">${people.map((p,i)=>`<div class="content-list-item"><span class="team-avatar" style="width:38px;height:38px;margin:0">${p[0]}</span><div class="list-text"><strong>${p[1]}</strong><p>${p[2]}</p></div><span class="status-pill ${i===0?'scheduled':'production'}">${p[3]}</span><button class="icon-button tiny" data-toast="إدارة صلاحيات ${p[1]}">···</button></div>`).join('')}</div><div class="section-top"><h3>الصلاحيات</h3></div><div class="page-grid"><article class="panel feature-card"><span class="feature-icon">♧</span><h3>المدير</h3><p>إدارة مساحة العمل، الأعضاء، المحتوى والتكاملات.</p></article><article class="panel feature-card"><span class="feature-icon" style="color:var(--violet);background:#a897ff17">✎</span><h3>المحرر</h3><p>إنشاء المحتوى وتحريره وإرساله إلى المراجعة.</p></article><article class="panel feature-card"><span class="feature-icon" style="color:var(--cyan);background:#70d8de17">◉</span><h3>المراجع</h3><p>مراجعة المحتوى وترك التعليقات قبل النشر.</p></article></div></div>`;}
function settingsView(){return `<div class="dashboard-grid"><article class="panel"><div class="panel-heading"><div><h2 class="panel-title">تفضيلات مساحة العمل</h2><div class="panel-caption">إعدادات الواجهة وتجربة الاستخدام</div></div></div><div class="setting-row"><div class="setting-copy"><strong>كثافة العرض</strong><small>استخدم مسافات أصغر لعرض المزيد من المعلومات</small></div><input class="switch" id="compact-setting" type="checkbox" ${state.compact?'checked':''} /></div><div class="setting-row"><div class="setting-copy"><strong>إشعارات المهام</strong><small>تنبيهات عند تعيين مهمة أو تغيير حالتها</small></div><input class="switch" type="checkbox" checked /></div><div class="setting-row"><div class="setting-copy"><strong>ملخص أسبوعي</strong><small>إرسال ملخص أداء الاستوديو كل يوم اثنين</small></div><input class="switch" type="checkbox" checked /></div><div class="setting-row"><div class="setting-copy"><strong>اللغة</strong><small>لغة واجهة لوحة التحكم</small></div><select class="select-pill"><option>العربية</option><option>English (قريباً)</option></select></div></article><article class="panel"><div class="panel-heading"><div><h2 class="panel-title">التكاملات</h2><div class="panel-caption">اربط القنوات والخدمات التي يستخدمها فريقك</div></div></div>${[['Instagram','حسابات النشر والتحليلات','◉'],['YouTube','الفيديوهات وأداء القناة','▶'],['Google Drive','ملفات الفريق وأصوله','▧'],['Slack','إشعارات الفريق','◌']].map((x,i)=>`<div class="setting-row"><div style="display:flex;align-items:center;gap:10px"><span class="feature-icon" style="width:30px;height:30px;font-size:13px">${x[2]}</span><div class="setting-copy"><strong>${x[0]}</strong><small>${x[1]}</small></div></div><button class="button button-quiet" data-toast="تكامل ${x[0]} غير موصول في هذه النسخة">${i===0?'إعداد':'ربط'}</button></div>`).join('')}</article></div><div class="panel" style="margin-top:14px"><div class="panel-heading"><div><h2 class="panel-title">حالة مساحة العمل</h2><div class="panel-caption">إعدادات المشروع في هذه المعاينة</div></div><span class="status-pill draft">واجهة أولية</span></div><p style="color:#929bad;font-size:10px;line-height:1.8;margin:0">المحتوى والمهام الجديدة تُحفظ في متصفحك الحالي فقط. يلزم إعداد قاعدة بيانات وخدمات خلفية قبل تفعيل الحسابات، المشاركة بين المستخدمين، النشر إلى القنوات، أو توليد الوسائط فعلياً.</p></div>`;}
function renderPage(page=state.page){state.page=page;document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('#breadcrumb-current').textContent=PAGE_NAMES[page];$('#page-title').innerHTML=page==='overview'?'صباح الإبداع، ياسلم <span class="wave">✳</span>':PAGE_NAMES[page];$('#page-subtitle').textContent=PAGE_SUBTITLES[page];let content='';switch(page){case'overview':content=renderOverview();break;case'content':content=contentView();break;case'library':content=libraryView();break;case'calendar':content=calendarView();break;case'analytics':content=analyticsView();break;case'workflows':content=workflowsView();break;case'team':content=teamView();break;case'settings':content=settingsView();break;}pageContent.innerHTML=content;bindPageActions();}
function toast(message){const node=document.createElement('div');node.className='toast';node.textContent=message;$('#toast-region').append(node);setTimeout(()=>node.remove(),3200);}
function openModal(){ $('#modal-overlay').hidden=false;setTimeout(()=>$('#content-title').focus(),30); }
function closeModal(){ $('#modal-overlay').hidden=true;$('#content-form').reset(); }
function askQuickTask(){const title=window.prompt('ما المهمة التي تريد إضافتها؟');if(!title||!title.trim())return;state.tasks.unshift({id:Date.now(),title:title.trim(),meta:'أضيفت للتو · اليوم',priority:'',done:false});save();renderPage();toast('تمت إضافة المهمة إلى قائمتك');}
function bindPageActions(){
  pageContent.querySelectorAll('[data-page]').forEach(el=>el.addEventListener('click',()=>renderPage(el.dataset.page)));
  pageContent.querySelectorAll('[data-new-content]').forEach(el=>el.addEventListener('click',openModal));
  pageContent.querySelectorAll('[data-toast]').forEach(el=>el.addEventListener('click',()=>toast(el.dataset.toast)));
  pageContent.querySelectorAll('[data-task]').forEach(el=>el.addEventListener('click',()=>{const task=state.tasks.find(t=>t.id===Number(el.dataset.task));if(task){task.done=!task.done;save();renderPage();}}));
  const filter=$('#content-filter');if(filter)filter.addEventListener('change',()=>{state.filter=filter.value;renderPage('content');});
  const quick=$('#quick-task');if(quick)quick.addEventListener('click',askQuickTask);
  const addTask=$('#add-task');if(addTask)addTask.addEventListener('click',askQuickTask);
  const invite=$('#invite-team');if(invite)invite.addEventListener('click',()=>toast('دعوات الأعضاء تحتاج إلى تفعيل المصادقة الخلفية'));
  const upload=$('#upload-asset');if(upload)upload.addEventListener('click',()=>toast('رفع الملفات يحتاج إلى إعداد تخزين خلفي'));
  const compact=$('#compact-setting');if(compact)compact.addEventListener('change',()=>{state.compact=compact.checked;document.body.classList.toggle('compact-mode',state.compact);save();toast('تم تحديث تفضيل العرض');});
}
document.querySelectorAll('.nav-item,.profile-button').forEach(el=>el.addEventListener('click',()=>{if(el.dataset.page)renderPage(el.dataset.page);}));
$('#new-content-button').addEventListener('click',openModal);
$('#invite-button').addEventListener('click',()=>toast('دعوات الأعضاء تحتاج إلى تفعيل المصادقة الخلفية'));
$('#close-modal').addEventListener('click',closeModal);$('#cancel-modal').addEventListener('click',closeModal);
$('#modal-overlay').addEventListener('click',e=>{if(e.target.id==='modal-overlay')closeModal();});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();const search=$('#global-search');search.focus();search.parentElement.classList.add('search-open');}});
$('#content-form').addEventListener('submit',e=>{e.preventDefault();const form=new FormData(e.currentTarget);const title=String(form.get('title')).trim();if(!title)return;const status=String(form.get('status'));state.content.unshift({id:Date.now(),title,type:String(form.get('type')),channel:String(form.get('channel')),status,date:'أضيف للتو · اليوم',symbol:'✦',cover:'',subtitle:'عنصر جديد'});save();closeModal();state.filter='all';renderPage('content');$('#draft-count').textContent=state.content.filter(c=>c.status==='draft').length;toast('تمت إضافة المحتوى إلى مساحة العمل');});
$('#notifications-button').addEventListener('click',()=>toast('لديك إشعاران: مراجعة تنتظر اعتمادك ومهمة تقترب من موعدها'));
$('#global-search').addEventListener('input',e=>{const term=e.target.value.trim().toLowerCase();if(state.page!=='content')renderPage('content');const rows=$$('.content-table tbody tr',pageContent);rows.forEach(row=>row.hidden=Boolean(term)&&!row.textContent.toLowerCase().includes(term));});
$('#global-search').addEventListener('search',()=>renderPage(state.page));
$('#mobile-menu').addEventListener('click',()=>{const side=$('#sidebar');side.classList.toggle('open');let scrim=$('.mobile-scrim');if(!scrim){scrim=document.createElement('div');scrim.className='mobile-scrim';document.body.append(scrim);scrim.addEventListener('click',()=>{side.classList.remove('open');scrim.classList.remove('active');});}scrim.classList.toggle('active',side.classList.contains('open'));});
renderPage('overview');
