"""Registered product modules and their honest implementation state."""
MODULES = [
    {"id": "dashboard", "title": "لوحة التحكم", "group": "الرئيسية", "icon": "⌂", "state": "READY"},
    {"id": "tasks", "title": "مركز المهام", "group": "التشغيل", "icon": "☷", "state": "READY"},
    {"id": "approvals", "title": "مركز الموافقات", "group": "التشغيل", "icon": "✓", "state": "READY"},
    {"id": "activity", "title": "سجل النشاط", "group": "التشغيل", "icon": "◷", "state": "READY"},
    {"id": "projects", "title": "المشاريع", "group": "التخطيط والتنفيذ", "icon": "▧", "state": "NOT_CONFIGURED"},
    {"id": "ai-team", "title": "فريق الذكاء الاصطناعي", "group": "أنظمة الذكاء الاصطناعي", "icon": "✣", "state": "NOT_CONFIGURED"},
    {"id": "ai-router", "title": "موجّه النماذج", "group": "أنظمة الذكاء الاصطناعي", "icon": "⌘", "state": "NOT_CONFIGURED"},
    {"id": "manus", "title": "Manus", "group": "أنظمة الذكاء الاصطناعي", "icon": "M", "state": "NOT_CONFIGURED"},
    {"id": "github", "title": "GitHub", "group": "أنظمة الذكاء الاصطناعي", "icon": "⌘", "state": "NOT_CONFIGURED"},
    {"id": "external-integrations", "title": "التكاملات الخارجية", "group": "التكاملات", "icon": "⇄", "state": "READY"},
    {"id": "characters", "title": "الشخصيات", "group": "الشخصيات والمحتوى", "icon": "◉", "state": "NOT_CONFIGURED"},
    {"id": "character-bibles", "title": "أدلة الشخصيات", "group": "الشخصيات والمحتوى", "icon": "▤", "state": "NOT_CONFIGURED"},
    {"id": "localization", "title": "التوطين", "group": "الشخصيات والمحتوى", "icon": "文", "state": "COMING_SOON"},
    {"id": "content", "title": "المحتوى", "group": "الإنتاج والنشر", "icon": "▧", "state": "NOT_CONFIGURED"},
    {"id": "production", "title": "الإنتاج", "group": "الإنتاج والنشر", "icon": "▶", "state": "NOT_CONFIGURED"},
    {"id": "media-vault", "title": "خزنة الوسائط", "group": "الإنتاج والنشر", "icon": "▣", "state": "NOT_CONFIGURED"},
    {"id": "publishing", "title": "النشر", "group": "الإنتاج والنشر", "icon": "↗", "state": "NOT_CONFIGURED"},
    {"id": "analytics", "title": "التحليلات", "group": "الإنتاج والنشر", "icon": "⌁", "state": "NOT_CONFIGURED"},
    {"id": "company-builder", "title": "منشئ الشركة", "group": "بناء الشركة", "icon": "⊞", "state": "READY"},
    {"id": "departments", "title": "الأقسام", "group": "بناء الشركة", "icon": "▦", "state": "READY"},
    {"id": "company-structure", "title": "الهيكل التنظيمي", "group": "بناء الشركة", "icon": "⌘", "state": "READY"},
    {"id": "workflows", "title": "سير العمل", "group": "بناء الشركة", "icon": "⟳", "state": "READY"},
    {"id": "tools", "title": "سجل الأدوات", "group": "بناء الشركة", "icon": "⌁", "state": "READY"},
    {"id": "knowledge-sources", "title": "مصادر المعرفة", "group": "بناء الشركة", "icon": "▤", "state": "READY"},
    {"id": "roles", "title": "الأدوار والصلاحيات", "group": "بناء الشركة", "icon": "◇", "state": "READY"},
    {"id": "security", "title": "الأمان", "group": "المنصة", "icon": "◇", "state": "READY"},
    {"id": "settings", "title": "الإعدادات", "group": "المنصة", "icon": "⚙", "state": "READY"},
]

BUILDER_CAPABILITIES = [
    {"id": "department", "title": "إضافة قسم", "state": "READY"},
    {"id": "manager", "title": "إضافة مدير ذكاء اصطناعي", "state": "READY"},
    {"id": "employee", "title": "إضافة موظف ذكاء اصطناعي", "state": "READY"},
    {"id": "worker", "title": "إضافة عامل ذكاء اصطناعي", "state": "READY"},
    {"id": "permissions", "title": "إدارة صلاحيات الموظفين", "state": "READY"},
    {"id": "character", "title": "إضافة شخصية", "state": "COMING_SOON"},
    {"id": "workflow", "title": "إنشاء أساس سير عمل", "state": "READY"},
    {"id": "tool", "title": "إضافة أداة", "state": "READY"},
    {"id": "knowledge-source", "title": "إضافة مصدر معرفة", "state": "READY"},
    {"id": "model", "title": "إضافة نموذج ذكاء اصطناعي", "state": "COMING_SOON"},
    {"id": "integration", "title": "إضافة تكامل", "state": "READY"},
]
